### ISSUE TITLE
[Sodium] No smooth lighting on structures with light blocks

### ISSUE THREAD

**Issue by hellyet** [CreativeMD/LittleTiles#1132]
**What I have:**
![Image](https://github.com/user-attachments/assets/375fcf83-4405-460b-b508-c13a37e31e60)
![Image](https://github.com/user-attachments/assets/3711b1b8-7b23-461d-8fbd-2fef81eb5e51)

**What expected to have:**

![Image](https://github.com/user-attachments/assets/b63f603b-db77-4ed5-ad00-34abaa033a11)
![Image](https://github.com/user-attachments/assets/2766f068-2831-44c6-9547-770e952794c1)

**Comment by CreativeMD** [comment]
What mods are you using?

**Comment by hellyet** [comment]
3d-Skin-Layers 1.7.5 (skinlayers3d)
		AE2WTLib 19.2.3 (ae2wtlib)
		AE2WTLib API 19.2.3 (ae2wtlib_api)
		AmbientSounds 6.1.11 (ambientsounds)
		AntiBlocksReChiseled 0.10.4 (antiblocksrechiseled)
		AppleSkin 3.0.7+mc1.21 (appleskin)
		Applied Energistics 2 19.2.12 (ae2)
		Applied Mekanistics 1.6.2 (appmek)
		Architectury 13.0.8 (architectury)
		Athena 4.0.1 (athena)
		Better Combat 2.2.4+1.21.1 (bettercombat)
		Better Third Person 1.9.0 (betterthirdperson)
		Biomes O' Plenty 21.1.0.12 (biomesoplenty)
		Born in Chaos  1.5.2 (born_in_chaos_v1)
		Caelus API 7.0.1+1.21.1 (caelus)
		Calypso's Candy Workshop 1.1.4 (ccw)
		CC: Tweaked 1.115.1 (computercraft)
		Chipped 4.0.2 (chipped)
		ClickThrough Plus 3.4+1.21.1 (clickthrough)
		Cloth Config v15 API 15.0.140 (cloth_config)
		Collective 8.3 (collective)
		Connected Glass 1.1.13 (connectedglass)
		CraftTweaker 21.0.27 (crafttweaker)
		CreativeCore 2.13.7 (creativecore)
		Curios API 9.5.1+1.21.1 (curios)
		Damage Numbers 1.4.1-neoforge (damagenumbers)
		Elytra Slot 9.0.2+1.21.1 (elytraslot)
		EMI 1.1.22+1.21.1+neoforge (emi)
		EMI Loot 0.7.6+1.21+neoforge (emi_loot)
		Entity Model Features 2.4.1 (entity_model_features)
		Entity Texture Features 6.2.9 (entity_texture_features)
		ExperienceLib 1.1.1 (experiencelib)
		Explorify 1.6.2 (explorify)
		Explosive Enhancement 1.1.2 (explosiveenhancement)
		ExtendedAE 1.21-2.2.12-neoforge (extendedae)
		Forgified Fabric API Base 0.4.42+d1308dedd1 (fabric_api_base)
		Forgified Fabric BlockView API (v2) 1.0.10+9afaaf8c19 (fabric_block_view_api_v2)
		Forgified Fabric Networking API (v1) 4.2.2+a92978fd19 (fabric_networking_api_v1)
		Forgified Fabric Renderer API (v1) 3.4.0+acb05a3919 (fabric_renderer_api_v1)
		Forgified Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 (fabric_rendering_data_attachment_v1)
		Forgified Fabric Screen API (v1) 2.0.24+79a4c2b0d1 (fabric_screen_api_v1)
		Fusion 1.2.7+b (fusion)
		Fzzy Config 0.7.0+1.21+neoforge (fzzy_config)
		GeckoLib 4 4.7.5.1 (geckolib)
		GlitchCore 2.1.0.0 (glitchcore)
		Glodium 1.21-2.2-neoforge (glodium)
		Gravestone Curios Compatibility 2.1.0 (gravestonecurioscompat)
		Gravestone Mod 1.21.1-1.0.24 (gravestone)
		GuideME 21.1.9 (guideme)
		Hit The Dummy 2.2.1 (mr_hit_thedummy)
		HT's TreeChop 0.19.3 (treechop)
		Immersive Paintings 0.6.8 (immersive_paintings)
		Inventory Profiles Next 2.1.9 (inventoryprofilesnext)
		Iris 1.8.12-snapshot+mc1.21.1-local (iris)
		ItemPhysic 1.8.6 (itemphysic)
		Jade 15.8.3+neoforge (jade)
		Just Zoom 2.1.0 (justzoom)
		Konkrete 1.9.9 (konkrete)
		Kotlin For Forge 5.8.0 (kotlinforforge)
		L_Ender's Cataclysm 2.66-1.21.1 (cataclysm)
		Leashable Villagers 1.3 (leashablevillagers)
		libIPN 6.5.0 (libipn)
		Lighty 3.0.0-beta.8 (lighty)
		lionfishapi 2.6 (lionfishapi)
		LittleTiles 1.6.0-pre171 (littletiles)
		macabre 0.7.3 (macabre)
		Magnum Torch 21.1.0 (magnumtorch)
		Mekanism 10.7.14 (mekanism)
		Mekanism Covers 1.3-BETA+1.21 (mekanismcovers)
		Mekanism Curios 1.2.1 (mekanismcurios)
		Mekanism Extras 1.21.1-1.2.1 (mekanism_extras)
		Mekanism Lasers 1.1.10.2 (mekanism_lasers)
		Mekanism Turrets 2.1.3 (mekanism_turrets)
		Mekanism Unleashed 1.21.1-0.3.2 (mekanism_unleashed)
		Mekanism: Additions 10.7.14 (mekanismadditions)
		Mekanism: Generators 10.7.14 (mekanismgenerators)
		Mekanism: Tools 10.7.14 (mekanismtools)
		Minecraft 1.21.1 (minecraft)
		MmmMmmMmmMmm 1.21-2.0.8 (dummmmmmy)
		Moonlight Lib 1.21-2.18.18 (moonlight)
		Mouse Tweaks 2.26.1 (mousetweaks)
		Mutant Monsters 21.1.0 (mutantmonsters)
		NeoForge 21.1.186 (neoforge)
		No Telemetry 1.9.0 (no_telemetry)
		Not Enough Recipe Book 0.4.2 (nerb)
		NotEnoughAnimations 1.9.3 (notenoughanimations)
		OctoLib 0.5.0.1 (octolib)
		Open Parties and Claims 0.24.2 (openpartiesandclaims)
		Oracle Index 0.3.0 (oracle_index)
		oωo 0.12.15.1-beta.3+1.21 (owo)
		ParCool! 3.4.0.5 (parcool)
		Player Animator 2.0.1+1.21.1 (playeranimator)
		Point Blank 1.9.6 (pointblank)
		Polymorph 1.0.10+1.21.1 (polymorph)
		Polymorphic Energistics 0.4.1 (polyeng)
		Potentials 0.6.2 (potentials)
		Puzzles Lib 21.1.36 (puzzleslib)
		Realistic Bees 4.2 (realisticbees)
		Rechiseled 1.1.6+a (rechiseled)
		Rechiseled: Chipped 1.2 (rechiseled_chipped)
		Reese's Sodium Options 1.8.3+mc1.21.4 (reeses_sodium_options)
		Relics 0.10.7.5 (relics)
		Reliquified L_Ender's Cataclysm 0.1 (reliquified_lenders_cataclysm)
		Resourceful Lib 3.0.12 (resourcefullib)
		Screenshot to Clipboard 1.0.10 (screenshotclipboard)
		Scribble 1.5.1 (scribble)
		Simply Swords 1.60.11-1.21.1 (simplyswords)
		Sky Aesthetics 1.6.1 (sky_aesthetics)
		Sodium 0.6.13+mc1.21.1 (sodium)
		Sodium Dynamic Lights 1.0.9 (sodiumdynamiclights)
		Sodium Extra 0.6.0+mc1.21.1 (sodium_extra)
		Sodium Options API 1.0.10 (sodiumoptionsapi)
		Sophisticated Backpacks 3.24.15 (sophisticatedbackpacks)
		Sophisticated Core 1.3.50 (sophisticatedcore)
		Sound Physics Remastered 1.21.1-1.4.10 (sound_physics_remastered)
		Soundbank 2.5.0 (soundbank)
		Stellaris 1.3.16 (stellaris)
		SuperMartijn642's Config Library 1.1.8 (supermartijn642configlib)
		SuperMartijn642's Core Lib 1.1.18+a (supermartijn642corelib)
		TerraBlender 4.1.0.8 (terrablender)
		Tom's Peripherals 1.3.0 (toms_peripherals)
		Traveler's Titles 1.21.1-NeoForge-5.1.3 (travelerstitles)
		underwater_village 1.0.2 (underwater_village)
		Universal Bone Meal 21.1.0 (universalbonemeal)
		Xaero's Minimap 25.2.6 (xaerominimap)
		Xaero's World Map 1.39.9 (xaeroworldmap)
		XaeroZoomout 2.0.0 (xaerozoomout)
		YUNG's API 1.21.1-NeoForge-5.1.5 (yungsapi)
		YUNG's Better Desert Temples 1.21.1-NeoForge-4.1.5 (betterdeserttemples)
		YUNG's Better Dungeons 1.21.1-NeoForge-5.1.4 (betterdungeons)
		YUNG's Better End Island 1.21.1-NeoForge-3.1.2 (betterendisland)
		YUNG's Better Jungle Temples 1.21.1-NeoForge-3.1.2 (betterjungletemples)
		YUNG's Better Mineshafts 1.21.1-NeoForge-5.1.1 (bettermineshafts)
		YUNG's Better Nether Fortresses 1.21.1-NeoForge-3.1.5 (betterfortresses)
		YUNG's Better Ocean Monuments 1.21.1-NeoForge-4.1.2 (betteroceanmonuments)
		YUNG's Better Strongholds 1.21.1-NeoForge-5.1.3 (betterstrongholds)
		YUNG's Better Witch Huts 1.21.1-NeoForge-4.1.1 (betterwitchhuts)
		YUNG's Extras 1.21.1-NeoForge-5.1.1 (yungsextras)

**Comment by CreativeMD** [comment]
Can you try it without Sodium Dynamic Lights and Sodium Extra?

**Comment by hellyet** [comment]
Sure.

**Comment by CreativeMD** [comment]
And?

**Comment by hellyet** [comment]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/4d6f1bf1-171b-4e00-bf60-759787775be7" />
And nothing changes.
And at my screenshot you can see an invisible door entity.

**Comment by CreativeMD** [comment]
Can you export the world so I can test it myself?

**Comment by hellyet** [comment]
I'll build a structure to demonstrate this issue.

**Comment by hellyet** [comment]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/7d5e18fb-2a80-4e1a-90d9-d45487b34ddb" />

Note, that you need to place some light around the structure for the best manifestation of Issue.

```
{boxes:23,grid:4,min:[I;0,0,2],s:{id:"fixed"},size:[I;16,12,2],t:{"minecraft:light_gray_concrete":[[I;-1],[I;0,0,2,4,4,4],[I;0,4,2,3,8,4],[I;3,4,2,4,8,3],[I;3,5,3,4,8,4],[I;0,8,2,4,12,4],[I;4,0,2,8,4,4],[I;4,4,2,8,8,3],[I;5,4,3,8,8,4],[I;4,5,3,5,8,4],[I;4,8,2,8,12,4],[I;8,0,2,12,4,4],[I;8,4,2,12,8,3],[I;8,4,3,12,6,4],[I;8,6,3,9,8,4],[I;11,6,3,12,8,4],[I;9,7,3,11,8,4],[I;8,8,2,12,12,4],[I;12,0,2,16,4,4],[I;12,4,2,16,8,4],[I;12,8,2,16,12,4]],"minecraft:sea_lantern":[[I;-1],[I;3,4,3,4,5,4],[I;4,4,3,5,5,4],[I;9,6,3,11,7,4]]},tiles:2}
```

**Comment by CreativeMD** [comment]
I have reported this issue to sodium as I cannot see something wrong from my end: https://github.com/CaffeineMC/sodium/issues/3227

**Comment by hellyet** [comment]
Fixed in Sodium 0.8.1 (for Minecraft 1.21.11).
Awaiting for minor update of 0.6.x (1.21.1) - https://github.com/CaffeineMC/sodium/milestone/20

**Comment by CreativeMD** [comment]
Might be fixed with the newest version from sodium and littletiles.

**Comment by hellyet** [comment]
Yeah, I'll test it ASAP

**Comment by DraGonFiirE** [comment]
Seems to be still an issue
<img width="1093" height="986" alt="Image" src="https://github.com/user-attachments/assets/5fa7895a-727c-4dc2-83d6-5aa96f7ce881" />

**Comment by CreativeMD** [comment]
But less, can you report it here as well?
https://github.com/CaffeineMC/sodium/issues/3227

**Comment by DraGonFiirE** [comment]
I just realised this also happens without sodium installed

**Comment by hellyet** [comment]
It seems to be more than just a Sodium lighting issue.
I would suggest dropping this issue.
